---
title: "Demo script"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Demo script}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
library(MutExMatSorting)
```

```{r}
library(pheatmap)

r <- 100
c <- 100

dens<-0.1
BinMat <- matrix(0, r, c,dimnames = list(paste('row',1:r,sep=''),paste('col',1:c,sep='')))
BinMat[sample(r*c,round(r*c*dens))]<-1

#Executing mutual exclusivity sorting
sortedMat<-MExMaS.HeuristicMutExSorting(BinMat)

#visualising original matrix
pheatmap(BinMat,cluster_rows = FALSE,cluster_cols = FALSE,
         legend = FALSE,show_colnames = FALSE,show_rownames = FALSE,main='Original Matrix',
         col=c('white','blue'))
```
```{r}
#visualising original matrix
pheatmap(sortedMat,cluster_rows = FALSE,cluster_cols = FALSE,
         legend = FALSE,show_colnames = FALSE,show_rownames = FALSE,main='Sorted Matrix',
         col=c('white','blue'))
```
